
-- PROJECT 1

-- Using the database
USE SQLProject1;

-- Using schema -- Using schema for easy differentiation between databases
CREATE SCHEMA gold

-- Exploring the database
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS

-- Starting our analyis
-- Exploring which countries our customers are from
SELECT 
DISTINCT country
FROM gold.dim_customers;

-- Explore all product categories under "The Major Divisions"
SELECT 
DISTINCT category, 
subcategory, 
product_name
FROM gold.dim_products
ORDER BY 1,2,3

-- Exploring the earliest and the lastest date
-- Find the date of the first and the last order and also find out how many years and months of sales we had
SELECT 
MIN(order_date) AS [FIRST ORDER], 
MAX(order_date) AS [LAST ORDER],
DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS [YEARS OF SALES],
DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS [MONTHS OF SALES]
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT MIN(birthdate) AS [OLDEST CUSTOMER], MAX(birthdate) AS [YOUNGEST CUSTOMER]
FROM gold.dim_customers;

-- Let's find out their actual age instead of birthdate
SELECT
DATEDIFF(YEAR, MIN(birthdate), CURRENT_DATE) AS [AGE OF OLDEST CUSTOMER],
DATEDIFF(YEAR, MAX(birthdate), CURRENT_DATE) AS [AGE OF YOUNGEST CUSTOMER]
FROM gold.dim_customers;


-- Measure exploration - to explore all the numerical measure of the data

-- Find the total sales amount
SELECT 
SUM(sales_amount) AS [TOTAL SALES]
FROM gold.fact_sales;

-- Find how many items are sold
SELECT
SUM(quantity) AS [TOTAL QUANTITY]
FROM gold.fact_sales;

-- Find the average selling price
SELECT
AVG(price) AS [AVG SELLING PRICE]
FROM gold.fact_sales;

-- Find the total number of orders
-- I will use distinct here as orders will contain duplicates. Customers might place one order that contains multiple products.
SELECT
COUNT(DISTINCT(order_number)) AS [TOTAL ORDERS]
FROM gold.fact_sales;

-- Find the total number of products
SELECT 
COUNT(product_key) AS [TOTAL PRODUCTS]
FROM gold.dim_products;

-- Find the total number of customers
SELECT 
COUNT(customer_id) AS [NUM OF CUSTOMERS]
FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT
COUNT(DISTINCT(c.customer_key)) AS [NUM OF CUSTOMERS THAT HAVE PLACED AN ORDER]
FROM gold.dim_customers c
JOIN gold.fact_sales s
ON c.customer_key = s.customer_key;


-- Analysing data by grouping them
-- Find the total number of customers by countries
SELECT
country,
COUNT(customer_id) AS [TOTAL NUM OF CUST]
FROM gold.dim_customers
GROUP BY country
ORDER BY [TOTAL NUM OF CUST] DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_id) AS [TOTAL NUM OF CUST]
FROM gold.dim_customers
GROUP BY gender
ORDER BY [TOTAL NUM OF CUST] DESC

-- Find the total products by category
SELECT
category,
COUNT(product_id) AS [TOTAL PRODUCTS PER CATEGORY]
FROM gold.dim_products
GROUP BY category
ORDER BY [TOTAL PRODUCTS PER CATEGORY] DESC;

-- What is the average cost in each category?
SELECT
category,
AVG(cost) AS [AVERAGE COST PER CATEGORY]
FROM gold.dim_products
GROUP BY category
ORDER BY [AVERAGE COST PER CATEGORY] DESC;

-- What is the total revenue generated for each category
SELECT
p.category,
SUM(s.sales_amount) AS [TOTAL REVENUE]
FROM gold.fact_sales s
JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY [TOTAL REVENUE] DESC;

-- What is the total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS [TOTAL SALES]
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY [TOTAL SALES] DESC;

-- What is the distribution of items sold across countries
SELECT
c.country,
SUM(s.quantity) AS [TOTAL QTY]
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY [TOTAL QTY] DESC;


-- Let's do some ranking

-- Which 5 products generate the highest revenue
SELECT TOP 5
p.product_name,
SUM(s.sales_amount) AS [TOTAL SALES]
FROM gold.dim_products p
INNER JOIN gold.fact_sales s
ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY [TOTAL SALES] DESC;

-- Which are the 5  worst performing products in terms of sales
SELECT TOP 5
p.product_name,
SUM(s.sales_amount) AS [TOTAL SALES]
FROM gold.dim_products p
INNER JOIN gold.fact_sales s
ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY [TOTAL SALES] ASC;

-- Find the top 10 customers who have generated the highest revenue and top 3 customers with the fewest orders placed

--HIGHEST
SELECT *
FROM (
	SELECT
	ROW_NUMBER () OVER (ORDER BY SUM(sales_amount) DESC) AS [RANK],
	c.first_name,
	c.last_name,
	SUM(sales_amount) AS [TOTAL REVENUE]
	FROM gold.fact_sales s
	INNER JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key
	GROUP BY c.first_name,c.last_name ) t
WHERE RANK <= 5;

-- LOWEST
SELECT TOP 3 *
FROM (
	SELECT
	ROW_NUMBER () OVER (ORDER BY SUM(sales_amount)) AS [RANK],
	c.first_name,
	c.last_name,
	SUM(sales_amount) AS [TOTAL REVENUE]
	FROM gold.fact_sales s
	INNER JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key
	GROUP BY c.first_name,c.last_name ) t